
[package]
name = "candela"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7.1", features = ["embed"] }
candle-core = "0.9.0"
