[package]
name = "candela"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6", features = ["embed"] }
candle-core = "0.9.0"

[build-dependencies]
magnus = { version = "0.6", features = ["embed"] }
magnus-export = "0.6"